# config/cucumber.yml
##YAML Template

ios: PLATFORM=ios -r features/support -r features/ios/ -r features/ios/support -r features/ios/helpers -r features/step_definitions -r features/ios/pages
 # APP_BUNDLE_PATH=ios-source/3.3.1/build/Applications/WordPress.app
